# Generated by Django 5.2.8 on 2026-01-01 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_rating', models.CharField(max_length=10, unique=True, verbose_name='Возрастной рейтинг')),
                ('min_age', models.SmallIntegerField(verbose_name='Минимальный возраст')),
            ],
            options={
                'verbose_name': 'Возрастной рейтинг',
                'verbose_name_plural': 'Возрастные рейтинги',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=30, unique=True, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='HallType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_type', models.CharField(max_length=20, unique=True, verbose_name='Тип зала')),
            ],
            options={
                'verbose_name': 'Тип кинозала',
                'verbose_name_plural': 'Типы кинозалов',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(True, 'Продан'), (False, 'Свободен')], default=False, verbose_name='Статус')),
                ('buy_date', models.DateField(blank=True, null=True, verbose_name='Дата покупки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
        ),
        migrations.CreateModel(
            name='CinemaHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.SmallIntegerField(verbose_name='Количество рядов')),
                ('seat_number_in_row', models.SmallIntegerField(verbose_name='Мест в ряду')),
                ('available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('hall_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.halltype', verbose_name='Тип зала')),
            ],
            options={
                'verbose_name': 'Кинозал',
                'verbose_name_plural': 'Кинозалы',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('duration', models.SmallIntegerField(verbose_name='Длительность (мин)')),
                ('release_year', models.SmallIntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Рейтинг')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='Постер')),
                ('age_rating', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.agerating', verbose_name='Возрастной рейтинг')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.genre')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie')),
            ],
            options={
                'verbose_name': 'Жанр фильма',
                'verbose_name_plural': 'Жанры фильмов',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(through='main.MovieGenre', to='main.genre', verbose_name='Жанры'),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.SmallIntegerField(verbose_name='Ряд')),
                ('seat_in_row', models.SmallIntegerField(verbose_name='Место в ряду')),
                ('cinema_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cinemahall', verbose_name='Кинозал')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_session', models.DateField(verbose_name='Дата сеанса')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('report', models.TextField(blank=True, null=True, verbose_name='Отчет')),
                ('cinema_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cinemahall', verbose_name='Кинозал')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеансы',
                'ordering': ['date_session', 'start_time'],
            },
        ),
    ]
