# Generated by Django 5.2.8 on 2026-01-01 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.seat', verbose_name='Место'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.session', verbose_name='Сеанс'),
        ),
        migrations.AlterUniqueTogether(
            name='moviegenre',
            unique_together={('movie', 'genre')},
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('cinema_hall', 'row', 'seat_in_row')},
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('session', 'seat')},
        ),
    ]
